export const G0 = {
  phase: "G0",
  spec: "v0.2",
  product: "Lumina Archive",
  verdict: "CONDITIONAL PASS",
  native: "BLOCKED BY ENVIRONMENT",
  baseline: "Bandizip 7.46",
  stack: [
    { layer: "Lumina.Win", tech: "C# / .NET 10.0.11 / WinUI 3 / WASDK 2.4.0" },
    { layer: "Domain", tech: "C# job/policy models" },
    { layer: "Supervisor", tech: "C# + Job Object + Named Pipe IPC" },
    { layer: "lumina-engine.exe", tech: "C++20 worker — codecs live only here" },
    { layer: "lumina-preview.exe", tech: "separate WIC process (G7)" },
    { layer: "lumina-shell.dll", tech: "IExplorerCommand, no parser" },
  ],
  pins: [
    { name: "7-Zip", version: "26.02", role: "unmodified 7z.dll" },
    { name: "minizip-ng", version: "4.2.2", role: "ZIP container" },
    { name: "zlib-ng", version: "2.3.3", role: "Deflate fast path" },
    { name: "ISA-L", version: "2.32.1", role: "optional x64 accel" },
    { name: "libdeflate", version: "1.25", role: "bench-gated" },
    { name: "libarchive", version: "3.8.9", role: "TAR/ISO, not ZIP hot path" },
    { name: "zstd / LZ4 / XZ / BLAKE3", version: "1.5.7 / 1.10.0 / 5.8.3 / 1.8.7", role: "codecs / hash" },
  ],
  invariants: [
    "웹·Electron·Tauri·Python GUI로 제품을 대체하지 않는다.",
    "코덱을 새로 구현하지 않는다.",
    "암호는 argv/환경변수/일반 로그에 넣지 않는다. 생산 경로는 7z.dll 콜백.",
    "UI와 Explorer에 파서를 로드하지 않는다.",
    "아카이브 경로는 전부 불신 입력이다.",
    "성능 주장은 bench/RESULTS.md 숫자만 사용한다.",
    "Gate가 PASS가 아니면 다음 Phase로 가지 않는다.",
  ],
  phases: [
    { id: "G0", title: "Constitution", state: "in-progress" },
    { id: "G1", title: "Bench harness", state: "blocked" },
    { id: "G2", title: "IPC + Supervisor", state: "planned" },
    { id: "G3", title: "7z.dll core", state: "planned" },
    { id: "G4", title: "Safe Extract", state: "planned" },
    { id: "G5", title: "Adaptive ZIP", state: "planned" },
    { id: "G6", title: "WinUI shell", state: "planned" },
    { id: "G7", title: "Power features", state: "planned" },
    { id: "G8", title: "Explorer / MSIX", state: "planned" },
    { id: "G9", title: "RC hardening", state: "planned" },
  ],
} as const;
